version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ChattyMoAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    depends_on:
      - postgres_database
    restart: unless-stopped
  postgres_database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=chattymo
      - POSTGRES_DB=chattymo
      - POSTGRES_PASSWORD=XmgqNG8PUuvFwj5F
    volumes:
      - postgres_database:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_database:
    driver: local